version: "3.8"
services:
  app_container:
    image:
    container_name: 
    build: 
      context: ./
    enviroment:
    deploy:
      replicas: 3
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
