version: '2'
services:
    web:
        build: .
        ports:
            - "5001:5001"
        volumes:
            - .:/code
        depends_on:
            - redis
    redis:
        image: redis
